/**
 * objectives.js — Aula Viva PASO 1: 8 objetivos estratégicos mapeados a
 * eventos canónicos + señales base. Contratos puros (sin compute).
 * Permite navegar: objetivo → qué eventos necesito → qué señales lo cubren
 * → qué falta → qué panel lo mostrará en PASO 3.
 */
export const OBJECTIVES = Object.freeze([
    { id: 'fluidez_lectora',
      required_events: ['reading_progress','immersive_sentence_committed','reading_completed','session_ended'],
      required_signals: ['fluidez_inferida','tiempo_efectivo_lectura'],
      data_gaps: ['palabras/contenido mapeado','anchors V2 universales','tasks fluencia opt-in'],
      precision_now: 'baja (proxy)', future_recommendations: ['retos fluencia adaptativos'],
      panel_paso3: 'lector_individual_y_grupo' },
    { id: 'comprension_lectora',
      required_events: ['guided_step_completed','reading_completed','reading_repeated_segment','leo_interaction_completed','leo_evidence_recorded'],
      required_signals: ['profundidad_sesion','relectura','dificultad_probable','inferencia_observada','metacognicion_observada'],
      data_gaps: ['quizzes/respuestas estructuradas (no en plataforma hoy)','las signals Leo son OBSERVADAS — no afirman comprensión'],
      precision_now: 'media (sin assessment formal)',
      future_recommendations: ['micro-tasks Leo verifican comprensión'],
      panel_paso3: 'lector_individual_y_grupo' },
    { id: 'persistencia',
      required_events: ['reading_resumed','reading_completed','reading_abandoned','reading_reopened'],
      required_signals: ['persistencia','recuperacion_tras_abandono'],
      data_gaps: [],
      precision_now: 'alta',
      future_recommendations: ['intervención cuando abandono>0.4'],
      panel_paso3: 'lector_individual_y_grupo' },
    { id: 'lectura_autonoma',
      required_events: ['reading_started','accessibility_mode_enabled','tts_started','leo_interaction_started'],
      required_signals: ['lectura_autonoma','uso_audio','mediacion_leo'],
      data_gaps: ['mediacion_leo invertido: alta frecuencia ≠ baja autonomía sin contexto'],
      precision_now: 'media',
      future_recommendations: ['progresión gradual a modo guiado'],
      panel_paso3: 'lector_individual' },
    { id: 'diversidad_lectora',
      required_events: ['reading_started','reading_completed'],
      required_signals: ['diversidad_lectora'],
      data_gaps: ['taxonomía de contenidos (género/dificultad/autor)'],
      precision_now: 'alta (cobertura) / media (calidad sin taxonomía)',
      future_recommendations: ['recomendaciones cross-género'],
      panel_paso3: 'grupo_y_institucion' },
    { id: 'lectura_critica',
      required_events: ['guided_prompt_opened','guided_step_completed','leo_interaction_completed','leo_evidence_recorded','album_interaction'],
      required_signals: ['profundidad_sesion','engagement','inferencia_observada','metacognicion_observada'],
      data_gaps: ['inferencia_observada y metacognicion_observada son OBSERVADAS — clasificación pedagógica del objetivo de la interacción, NO juicio sobre comprensión real'],
      precision_now: 'baja',
      future_recommendations: ['prompts Leo específicos: inferencia/contraargumento'],
      panel_paso3: 'lector_individual' },
    { id: 'concentracion',
      required_events: ['immersive_visibility_stall','session_heartbeat','reading_paused','session_timeout'],
      required_signals: ['concentracion','tiempo_efectivo_lectura'],
      data_gaps: [],
      precision_now: 'alta (en modo inmersivo)',
      future_recommendations: ['nudges contextuales tras stalls repetidos'],
      panel_paso3: 'lector_individual' },
    { id: 'construccion_habito',
      required_events: ['session_started','session_ended','reading_started','reading_completed'],
      required_signals: ['continuidad_semanal','engagement'],
      data_gaps: [],
      precision_now: 'alta',
      future_recommendations: ['streak goals adaptativos por cohort'],
      panel_paso3: 'lector_individual_y_grupo' },
]);

export const OBJECTIVE_IDS = Object.freeze(OBJECTIVES.map(o => o.id));
export function getObjective(id) { return OBJECTIVES.find(o => o.id === id) ?? null; }
